### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte

### ISSUE THREAD

**Issue by Wmengti** [fluencelabs/dev-rewards#10]
Traceback (most recent call last):
  File "/claim/python/proof.py", line 157, in <module>
    main()
  File "/claim/python/proof.py", line 141, in main
    sshPubKey, sshKeyPath = choose_ssh_key()
  File "/claim/python/proof.py", line 61, in choose_ssh_key
    if not is_ssh_key(path):
  File "/claim/python/proof.py", line 96, in is_ssh_key
    key = file.read()
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte

**Comment by leo-web3** [comment]
```python
def choose_ssh_key():
    files = []
    try:
        files = os.listdir(SSH_KEYS_DIR)
    except FileNotFoundError:
        pass

    sshKeys = []
    for f in files:
        if f == '.DS_Store':
            continue
        path = os.path.join(SSH_KEYS_DIR, f)
        if not is_ssh_key(path):
            continue
        sshKeys.append(path)
```

**Comment by Wmengti** [comment]
the same problem you meet ? I have tried this but it is still not work

**Comment by leo-web3** [comment]
Modify the code here

**Comment by Wmengti** [comment]
thanks. it works, but new problem with "Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys are supported for proof generation."
