### ISSUE TITLE
Is this airdrop completely anonymous?

### ISSUE THREAD

**Issue by c0mm4nd** [fluencelabs/dev-rewards#100]
As a developer, I have already seen a lot of spam emails related to this airdrop project, indicating that they are able to know whether I or other developers are eligible for the airdrop. First, I want to ask how they achieved this - is it through username brute-forcing or directly parsing from metadata?

Additionally, I have a more important question related to the anonymity of Ethereum accounts. Assuming I am an attacker, would I be able to match the on-chain token claim transaction records with my GitHub username (possibly through my public key)?

**Comment by akim-bow** [comment]
> First, I want to ask how they achieved this - is it through username brute-forcing or directly parsing from metadata?
I think they took all usernames in metadata file and parsed emails either by GitHub API or direct scraping.

> Assuming I am an attacker, would I be able to match the on-chain token claim transaction records with my GitHub username (possibly through my public key)?
Only in case if a victim mentioned etherium address for claiming somewhere in GitHub, i guess. If you know an user's wallet, then you can check a wallet's transactions.

**Comment by c0mm4nd** [comment]
I see there is a `userId` in EVM call `claimTokens(uint32 userId,bytes32[] merkleProof, address temporaryAddress, bytes signature)`, does this match the GitHub one in the [API](https://api.github.com/users/c0mm4nd)? 

And can the signature/merkleProof be verified by any one of the public keys in [my key list](https://github.com/c0mm4nd.keys)?

**Comment by c0mm4nd** [comment]
Thanks for your clear reply!
