### ISSUE TITLE
What private key?

### ISSUE THREAD

**Issue by Ex4byt3** [fluencelabs/dev-rewards#104]
I have my Github account but I don't know what private key the script is looking for. Where exactly am I supposed to find this?

**Comment by boneyard93501** [comment]
the one used to generate the public key that was available for snapshot
.ssh dir

**Comment by Ex4byt3** [comment]
> the one used to generate the public key that was available for snapshot .ssh dir

And if that key has since been deleted? Am I simply out of luck?
