### ISSUE TITLE
Account key replacement lost

### ISSUE THREAD

**Issue by 1165863642** [fluencelabs/dev-rewards#107]
After verification, my account is qualified, but the original key has been updated. How can I solve this problem?

**Comment by zoep** [comment]
I have the same issue, they do not seem willing to solve it. [Here](https://blog.fluence.network/fluence-developer-community) they say "If our account is eligible for a reward but you lost your private key, you will not be able to create a valid proof and unlock the reward."

**Comment by RuslanGlaznyov** [comment]
Do developers who make secret rotations and care about cyber security not deserve tokens in the Fluence team's opinion?

**Comment by folex** [comment]
You can only use SSH keys that were published in your GitHub profile at the time before Dev Reward has started. Key must be either ed25519 or RSA. And you need access to the private key part of the keypair.

Please read here for more info http://blog.fluence.network/fluence-developer-community/
