### ISSUE TITLE
metadata.bin doesn't exist

### ISSUE THREAD

**Issue by tangminjie** [fluencelabs/dev-rewards#11]
Why is there no metadata.json after I install it and run python3 python/proof.py?
![0d397b7250eb6f65f225b90b5babe5a](https://github.com/fluencelabs/dev-rewards/assets/66615553/82409090-4a5f-4b14-b85e-bfbd6ee4c854)
![1709191198380](https://github.com/fluencelabs/dev-rewards/assets/66615553/b1930351-c050-45b1-9062-dea12afef159)

**Comment by goku54477** [comment]
Getting the same error

![image](https://github.com/fluencelabs/dev-rewards/assets/118243927/f34afe59-d247-4cd7-8ee6-79fc3c8668fe)

**Comment by elshan-eth** [comment]
You can also download it manually

```
curl --progress-bar -o metadata.bin https://fluence-dao.s3.eu-west-1.amazonaws.com/metadata.bin
curl --progress-bar -o metadata.json https://fluence-dao.s3.eu-west-1.amazonaws.com/metadata.json
```
