### ISSUE TITLE
I won 5000FTL, why can’t I claim the prize?

### ISSUE THREAD

**Issue by lnsane** [fluencelabs/dev-rewards#110]
Welcome to the proof generation script for Fluence Developer Reward Airdrop.
5% of the FLT supply is allocated to ~110,000 developers who contributed into open source web3 repositories during last year.
Public keys of selected Github accounts were added into a smart contract on Ethereum. Claim your allocation and help us build the decentralized internet together!

Check if you are eligible and proceed with claimingEnter your github username so we can check if you are participating in the airdrop: lnsane

Ethereum wallet address is necessary to generate a proof that you will send through our web page.
Important notice: you need to make a claim transaction from the entered address!

Enter the ethereum address to which you plan to receive the airdrop: 0x1------------------------------------------
Found an encrypted key for your GitHub username

        NOTE: your SSH key is used ONLY LOCALLY to decrypt a message and generate Token Claim Proof.
        Script will explicitly ask your consent before using the key.
        If you have any technical issues, take a look at /home/azureuser/dev-rewards/__sh_cache__/openssl.stderr and /home/azureuser/dev-rewards/__sh_cache__/age.stderr files and report to https://fluence.chat

Now the script needs your ssh key to generate proof.
Enter path to the private SSH key to use or just press Enter to show existing keys:

Will use SSH key to generate proof data. Press enter to proceed.

is error

Couldn't decrypt with that SSH key, please choose another one.
Possible causes are:
You have specified the file which doesn't contain valid private key.
Your private key doesn't match your public key in GitHub. It could happen if you've changed local ssh key recently.
Internal ape error:
age: error: no identity matched any of the recipients
age: report unexpected or unhelpful errors at https://filippo.io/age/report

Why is it that I generated a new ssh_keys but it is still useless? I'm really speechless

**Comment by folex** [comment]
You can only use SSH keys that were published in your GitHub account at the time before Dev Rewards have started.

Please, read here for more info https://blog.fluence.network/fluence-developer-community/
