### ISSUE TITLE
Concern: I'm getting FLT-DROP intead of $FLT

### ISSUE THREAD

**Issue by CeoFred** [fluencelabs/dev-rewards#111]
I understand to some extent the idea of locking tokens. After the lock time, how do we convert this placeholder FLT-DROP tokens to actual $FLT?

**Comment by KodeSage** [comment]
@skylenet @alari @rvagg @elshan-eth
 please answer

**Comment by folex** [comment]
That's alright, that's what meant to happen. Please read here for more info http://blog.fluence.network/fluence-developer-community/

**Comment by BillZong** [comment]
Thanks for the information. 🙏
I suggest pinning this issue will ease everyone's confusion.

**Comment by realrouse** [comment]
@folex that blog post doesn't really answer @CeoFred's question. The blog post just says "Yes, you will be able to exchange them".

The question was: **How** will they be exchanged?

**Comment by CeoFred** [comment]
Thank you! Exactly my question
How?? Where?? We kinna know when

**Comment by siexp** [comment]
@CeoFred I suppose this is the answer to part of your question sir

>Can I exchange the airdrop tokens?
>You can exchange them to FLT after the 2 months lock up period since claiming.

Most likely exchange-contract will be announced closer to unlock date

https://blog.fluence.network/fluence-developer-community/

**Comment by siexp** [comment]
@CeoFred I suppose the answer is in the FLT-DROP SC code

```Solidity
    function transfer(address to, uint256 value) external returns (bool) {
        require(value > 0, "Value is 0");
        require(lockedBalances[msg.sender].amount == value, "Invalid amount");
        require(block.timestamp > lockedBalances[msg.sender].unlockTime, "Tokens are locked");

        lockedBalances[msg.sender].amount = 0;
        _totalSupply -= value;
        IERC20(token).safeTransfer(msg.sender, value);
        emit Transfer(msg.sender, address(0x00), value);

        return true;
    }
```

Briefly, this function transfer FLT equal to locked FLT-DROP amount. You can check your unlock amount with this method `lockedBalances` providing it with the address of the account that own FLT-DROP https://etherscan.io/address/0x6081d7f04a8c31e929f25152d4ad37c83638c62b#readContract#F13

https://etherscan.io/address/0x6081d7f04a8c31e929f25152d4ad37c83638c62b#code

P.S.
Please, always double-check links, addresses, contracts, etc you interact on-chain. trust no one

**Comment by CeoFred** [comment]
yea, just verified the token address and i'm certain that's how to make the claim. Thanks for this

**Comment by zommuter** [comment]
As an aside you can copy-paste the `unlockTime` to e.g. https://www.unixtimestamp.com/ to convert it to a readable date and time. Fun fact: I only learned about this airdrop from whom I first suspected to be a scammer, but for once my favorite quote 

> Have faith in the possibility of good - [_Q.U.B.E. director's cut (link contains spoilers)_](https://pixelpoppers.com/2018/05/faith-in-the-possibility-of-good-a-close-reading-of-q.u.b.e-directors-cut/)

applies :blush:

**Comment by zommuter** [comment]
Just an FYI update, I can confirm `transfer` works after the unlock time, but you must request the entire amount at once and the provided recipient is actually ignored but instead everything is unlocked to the same address
