### ISSUE TITLE
Error: cannot estimate gas

### ISSUE THREAD

**Issue by amiremohamadi** [fluencelabs/dev-rewards#115]
when i submit my proof i get this error in the console tab of my browser:

`Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Invalid signature", method="estimateGas", transaction=..., code=UNPREDICTABLE_GAS_LIMIT`

And in the next page, the claim button does not work.

![2024:03:31:09:31:28](https://github.com/fluencelabs/dev-rewards/assets/31338382/3a785963-47c8-4e91-b790-63997fd75d75)

**Comment by amiremohamadi** [comment]
there's a problem in the bash script. solved using the python script.

**Comment by amiremohamadi** [comment]
still when i click on the claim button it does not go to the next page

**Comment by Ifdevil** [comment]
thk,it works
