### ISSUE TITLE
All steps were completed, but FLT did not transfer to my own account.

### ISSUE THREAD

**Issue by danpi** [fluencelabs/dev-rewards#123]
Hi, I met a strange problem.  I followed the steps to submit the proof and finish the transaction, but I noticed that my personal account didn't get the FLT. 

Look at this! I finished the transaction on April 3rd. But I can't find any FLT in my trust wallet now. What should I do to solve this problem？
![image](https://github.com/fluencelabs/dev-rewards/assets/6015134/d3bc031e-b0f5-4562-93c0-4549c6fdf2a8)

![image](https://github.com/fluencelabs/dev-rewards/assets/6015134/91402135-c3ce-4785-b3dd-2bdcf03c71b2)

**Comment by justprosh** [comment]
Hi! Your tokens have been locked for two months since claiming. You should wait and then convert them to FLT with this button on the same [website](https://claim.fluence.network/)
<img width="261" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/24271614/8d4909b3-7752-40f5-8c92-7db6f0d145b1">

**Comment by danpi** [comment]
> Hi! Your tokens have been locked for two months since claiming. You should wait and then convert them to FLT with this button on the same [website](https://claim.fluence.network/) <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/24271614/332592007-8d4909b3-7752-40f5-8c92-7db6f0d145b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzM2NjAsIm5iZiI6MTcxNzU3MzM2MCwicGF0aCI6Ii8yNDI3MTYxNC8zMzI1OTIwMDctOGQ0OTA5YjMtNzc1Mi00MGY1LThjOTItN2RiNmYwZDE0NWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA3NDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZDhmODQzYWRjZTZmMmVkNDRkMGM4NjJjMTRmZTlmOWY3YzRmYjBiMzczMzc4YjU2M2ExNmNkMjUzNGViOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c4LSBw98-nFOtNOwuIiut8H7z7AVhNzrYpdJxcwAenw">

You are right. Some time ago I could see that I received 5000 FLTS. 
![image](https://github.com/fluencelabs/dev-rewards/assets/6015134/da730a74-b858-4e67-a83e-a989ad699da5)

But when I tried to check them today, my FLTs were gone and instead I clicked on the previous record to pop up this message. What should I do to solve this problem? @justprosh 
![image](https://github.com/fluencelabs/dev-rewards/assets/6015134/a6e27990-b1b5-418d-82ef-8d8db02a269d)
