### ISSUE TITLE
Unable to claim FLT tokens though github username is eligible for airdrop

### ISSUE THREAD

**Issue by rajeebkm** [fluencelabs/dev-rewards#124]
I've recently upgraded my laptop to a new device, and consequently, I'm encountering difficulty generating the Merkle proof from the local SSH key stored on this new device. I'm seeking advice on potential solutions for this issue.

Additionally, I'm interested in exploring alternative methods for claiming FLT tokens. Given the possibility of changes to the local SSH key due to factors such as device upgrades, job transitions, or oversight in backing up the private key, I'm keen to know if there are alternative verification processes in development.

<img width="1166" alt="Screenshot 2024-04-13 at 22 15 14" src="https://github.com/fluencelabs/dev-rewards/assets/97892873/8b177282-bc25-4acd-b73c-47f0c92d2581">

**Comment by boneyard93501** [comment]
without the private ssh key matching the public key captured by the snapshot, you will not be able to claim. see https://blog.fluence.network/fluence-developer-community/
