### ISSUE TITLE
This'xxxxx' Github account is not eligible for claiming

### ISSUE THREAD

**Issue by zhiyuan2007** [fluencelabs/dev-rewards#13]
Github account is not eligible for claiming, but ,  claim page show 5000 FLT

**Comment by CodingJzy** [comment]
what?

**Comment by CodingJzy** [comment]
一个是大小写的问题

**Comment by zhiyuan2007** [comment]
key code:
`ENCRYPTED_KEYS=()
 while IFS='' read -r line; do ENCRYPTED_KEYS+=("$line"); done < <(grep "^${GITHUB_USERNAME}," "${METADATA_BIN}" ||   true)`

git username is only eligible when in the metadata.bin ， rather than metadata.json
right?

**Comment by elshan-eth** [comment]
Unfortunately, "xxxxx" does not participate in aridrop
