### ISSUE TITLE
my flt send error

### ISSUE THREAD

**Issue by iohannes-long** [fluencelabs/dev-rewards#137]
when i send some flt to 0x2Cf3Db46993f3004d73E749b5B8e60249958bD0A address by matemask, but it be put into 0x6081d7F04a8c31e929f25152d4ad37c83638C62b. how can i get my flt back.
the trade info: https://etherscan.io/tx/0x12a0a0b46cc26f86610fd858e8d568f96d832f4d078b6ab9c3b44ff446b974f8
<img width="258" alt="1718084596715" src="https://github.com/fluencelabs/dev-rewards/assets/7234717/a12feca5-fd2e-43bd-a696-1e403958c995">

**Comment by iohannes-long** [comment]
it's still in matemask, i input the flt contact 0x236501327e701692a281934230AF0b6BE8Df3353, them back again.

**Comment by profclems** [comment]
Hi @ad-long, how were you able to convert the FLT-DROP to FLT? I claimed mine and still haven't received the FLT back https://etherscan.io/tx/0x1c90b70f1f02f05442d22bb71cd18786720c74c2853030097aa54652ae1cd9a4
