### ISSUE TITLE
age doesn't support yubikey decrypt

### ISSUE THREAD

**Issue by yvvw** [fluencelabs/dev-rewards#16]
ssh key store in gpg and gpg store in yubikey. it can't decrypt by age

**Comment by elshan-eth** [comment]
Unfortunately, we do not support hardware keys

**Comment by andresilva** [comment]
If someone adds a new SSH key to their profile can that one be used? I assume a lot of security-conscious people are using hardware keys, providing no solution for this is a bit shitty imo.

**Comment by elshan-eth** [comment]
Unfortunately, these are the conditions of this airdrop. Only RSA and Ed25519 keys without hardware support. If your key is on Yubikey or the old key is lost, then under the terms of the airdrop you are not a participant.

**Comment by du5** [comment]
No support for hardware keys This is a very bad decision
