### ISSUE TITLE
Please redact age report URL from error output

### ISSUE THREAD

**Issue by FiloSottile** [fluencelabs/dev-rewards#19]
Hello, age author here. A few of your users are getting errors which include a https://filippo.io/age link, and they are following that link seeking support on my issue tracker.

https://github.com/FiloSottile/age/issues/544

I obviously can't help them. Would you mind redacting those links?

**Comment by elshan-eth** [comment]
I apologize for this mistake. We'll fix it. Thank you!

**Comment by AnomalRoil** [comment]
Just chiming in to say that it might be nice of you to consider including github.com/FiloSottile/age in the eligible repos since you use it for the drop

**Comment by FiloSottile** [comment]
The age link is still displayed (see https://github.com/FiloSottile/age/issues/553), and we're still getting reports, which is frankly getting annoying.

**Comment by viraj124** [comment]
@elshan-eth I opened the latest issue what is the workaround this ?
this claiming process is def annoying is there a way to do a github auth on the ui and claim tokens that way ?

**Comment by mmaker** [comment]
I am claiming my rewards only because it's @FiloSottile's code, definitely should be included!
