### ISSUE TITLE
Proof has invalid format

### ISSUE THREAD

**Issue by atapin** [fluencelabs/dev-rewards#20]
RPC calls to `https://mainnet.gateway.tenderly.co/` fail with 429 error:

```
{
    "id": "1709215671619515648",
    "jsonrpc": "2.0",
    "error": {
        "code": -32005,
        "message": "rate limit exceeded"
    }
}```

**Comment by 1997roylee** [comment]
Same, Returned error: daily request count exceeded, request rate limited

**Comment by elshan-eth** [comment]
wow, thanks for the report. We will fix it.
