### ISSUE TITLE
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys are supported for proof generation. YOUR SCIRPT HAS PROBLEMS ,DONT CLOSE MY TICKET !!!!!!!!!!!!! 

### ISSUE THREAD

**Issue by GalaxySciTech** [fluencelabs/dev-rewards#21]
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys are supported for proof generation. 
<img width="805" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/30950645/4dd05783-8bc8-444d-9a1b-41ffcf1a32af">

everything is good , only your script error, 

YOUR SCIRPT HAS PROBLEMS ,DONT CLOSE MY TICKET !!!!!!!!!!!!!

**Comment by GalaxySciTech** [comment]
last ticket [](https://github.com/fluencelabs/dev-rewards/issues/7)

**Comment by FlorianRuen** [comment]
I got the exact same problem when using the script. Tried with both Python and shell script
In the past, I didn't have any SSH key registered to my account (only GPG keys for commits

![Capture d’écran du 2024-02-29 16-53-13](https://github.com/fluencelabs/dev-rewards/assets/13837778/a2e8eccd-027c-4e89-aaf1-f11929c1a850)
)

![Capture d’écran du 2024-02-29 16-52-05](https://github.com/fluencelabs/dev-rewards/assets/13837778/caf285ac-0692-4ffd-9a21-23dc558d03fe)

**Comment by elshan-eth** [comment]
@GalaxySciTech, you use this key, right?
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGHB72knEgoEtqsSme3lN3hjv6uqYlw9RZuRKbLEjsLF`

**Comment by elshan-eth** [comment]
@FlorianRuen, our airdrop contains this your public key. Does it match what you are trying to use?
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWxp5wYrIlnPwI/FyH7Vtp4QXg8mFWgS9qtorye8IMb/Gjcs7+3ql3GPhfUFmuecj8auZ30UK9DPCnqADJxzqvhjC31aomNYtF9PWzQHWNYkQnd+VTUzAcV7txO0O1cb8lyuXiGX+pWzYFG00tCz56jyCZHaQy0/gqmo5CZIYQ8veKy9NqDiNT89YRlXboOB+p7y0b8OicR9DOXdf4nlqZbNGQ4aDJ4eija/H05PDndvRpj5oC+xLbE/H2creg0JkiBMGqC0I8FqdYkCLNHHjpejuYGPsQnG8RLwGeCRQD/uZ9iPixL+x8yuOMUMo+RarE3PeE/BGMWLhj8Zf1h6alvan6l5oaPbfnKV8Tr/5fACjTsJbXuXDP3qhWRS/C4nOjVip15vIpERZ5k9cyfSokY4BwTjI8NEhoiVBNOOBR1B6fHsprABD8dEOhl45s9XRRFeFHhWVJ6pqaBhQdwyjcOue6/lGJSOpkZoGsN0iGGj9czCR7inc98gHuwnJzGNk=`

**Comment by FlorianRuen** [comment]
@elshan-eth I didn't have an ssh key on my github account before yesterday, how was this key retrieved ?
Because I can't find the attached private key on my vault

**Comment by elshan-eth** [comment]
@FlorianRuen We took a snapshot of public keys from GitHub. Unfortunately, if you created the key yesterday or after this snapshot, then you cannot receive the airdrop

**Comment by FlorianRuen** [comment]
@elshan-eth Strange, because I did not have a public key on my github account before yesterday, maybe the snapshot was a long time ago, this authentication method is not the best, since many github account changes ...

**Comment by petscheit** [comment]
Agreed. I updated to PATs a while ago and my old SSH key is on my old machine which has been wiped. Not a great authentication mechanism.

**Comment by FrostStarBook** [comment]
https://github.com/FiloSottile/age/issues/544    
Many people seem to have the same issue. When the script prompted us to provide feedback via the link, it seems we may have been directed to the wrong place to submit feedback.

My previous computer was a 2019 MacBook Pro. Last December, I switched to a new computer, and I wiped the data on the old one. However, my GitHub was configured with SSH from the old computer. I've removed that configuration now. I thought others might be in the same situation, using new SSH keys. @elshan-eth

**Comment by leo-web3** [comment]
I hope the project developers can solve this problem. This verification mechanism is very unfriendly. SSH key is not a friendly verification mechanism. There is also an oauth mechanism that can verify everyone on Github.
@elshan-eth

**Comment by GalaxySciTech** [comment]
> @FlorianRuen We took a snapshot of public keys from GitHub. Unfortunately, if you created the key yesterday or after this snapshot, then you cannot receive the airdrop

My key was from a year ago and was lost in the old machine. How do I receive the airdrop now?

**Comment by elshan-eth** [comment]
Unfortunately, if your active key is not in the airdrop, this means that you cannot receive the airdrop. It is airdrop conditions

**Comment by 106umao** [comment]
Why close this issue? Can’t the open status be seen by more developers? Save everyone’s time wasted on meaningless operations caused by your so-called snapshots.

**Comment by 106umao** [comment]
You can refer to issue #40 

@FlorianRuen
@GalaxySciTech
@leo-web3 
@FrostStarBook
@petscheit

**Comment by FlorianRuen** [comment]
Thanks for flagging @106umao, but I think I don't have my private key anymore, was a very old SSH Key, and my computer was restore/wiped few times since the creation

I said again, that this authentication method is not the best ...

**Comment by FrostStarBook** [comment]
<img width="1291" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/28086155/b2781df4-410f-4d24-ae2c-13c38a42f45d">

**Comment by FlorianRuen** [comment]
@FrostStarBook Thanks for this screenshot, and many github accounts use GPG key to sign commits not SSH keys, so many SSH keys can be inactive, except for account that use SSH to pull/commits ...

**Comment by elshan-eth** [comment]
This is an airdrop and it has these conditions. If you don't have the key from our snapshot, you are not a participant in the airdrop.
