### ISSUE TITLE
Error: Invalid signature. Are you using the same wallet you specified in proof generation?

### ISSUE THREAD

**Issue by pyropy** [fluencelabs/dev-rewards#22]
Hi, I've generated proof using the wallet I got connected on the website. When trying to submit proof I get following error : "Invalid signature. Are you using the same wallet you specified in proof generation?" 

Looking in the console I got following error logged from metamask:  "execution reverted: Invalid signature"

**Comment by pyropy** [comment]
Issue has been somehow resolved, not sure what happened. I've refreshed the page couple of times and now it works 🤷🏻‍♂️

**Comment by nautaa** [comment]
I also get this message.

**Comment by whatqiu** [comment]
How did you solve the problem 😭
