### ISSUE TITLE
Current reward shows 0 FLT

### ISSUE THREAD

**Issue by tsreaper** [fluencelabs/dev-rewards#23]
Current reward shows 0 FLT and after submitting my proof I can claim null FLT. Is this intended?

![image](https://github.com/fluencelabs/dev-rewards/assets/19909549/90a92196-edf8-4728-89ed-bc8f4f7bad8c)

![image](https://github.com/fluencelabs/dev-rewards/assets/19909549/e99c3efb-04fd-4358-a48d-30a4b58ebd96)

**Comment by 1997roylee** [comment]
same issue

**Comment by myNameIsDu** [comment]
same issue

**Comment by elshan-eth** [comment]
This is a frontend bug. Most likely your tokens are already on your balance. Please, check your balance in etherscan account. 
Token address: https://etherscan.io/token/0x6081d7F04a8c31e929f25152d4ad37c83638C62b

**Comment by elshan-eth** [comment]
Let me know if this is not the case. We will soon correct the error for the frontend.

**Comment by akim-bow** [comment]
Show be fixed by now.
