### ISSUE TITLE
docker build -t dev-reward-script . error

### ISSUE THREAD

**Issue by Yang122333** [fluencelabs/dev-rewards#24]
This step cannot be completed, but I can run the problematic line separately in PowerShell: curl -o metadata.json ...
![7411709228152_ pic](https://github.com/fluencelabs/dev-rewards/assets/37656169/048af853-7469-472e-b038-239df5cb08f4)

**Comment by akim-bow** [comment]
Seems like network interruptions while `curl` is downloading the file. You can try other approaches(bash and python) to get your claim.
