### ISSUE TITLE
Will the github ssh key data in metadata be updated on a regular schedule?

### ISSUE THREAD

**Issue by ysh0566** [fluencelabs/dev-rewards#36]
I have been using the GitHub token all the time, so the SSH key configuration was incorrect. I have now updated the SSH key configuration with a new one.

**Comment by akim-bow** [comment]
Not planned for now. Watch for the announcements in our socials in case this will be introduced. 
[Discord](https://fluence.chat/)
[Twitter](https://twitter.com/fluence_project)
