### ISSUE TITLE
clicked 'claim 5000 FLT' but no finish state

### ISSUE THREAD

**Issue by Bisstocuz** [fluencelabs/dev-rewards#38]
![image](https://github.com/fluencelabs/dev-rewards/assets/42398278/b3ea8d2c-8be0-4fd7-9ce5-061fd2d3a907)

I followed instructions step by step and then clicked this button but nothing happened: https://claim.fluence.network/done

**Comment by akim-bow** [comment]
@Bisstocuz any logs or errors in the console?

**Comment by Bisstocuz** [comment]
> @Bisstocuz any logs or errors in the console?

no any another error logs except request to `https://eth-mainnet.g.alchemy.com/v2/mTpanVgvjVVRocxu5nkJUjgcDnBcxPrr` for method `test` returned status code `400`.

**Comment by Bisstocuz** [comment]
![image](https://github.com/fluencelabs/dev-rewards/assets/42398278/cd509501-0ffd-45bc-827b-9e21b9301cc6)
![image](https://github.com/fluencelabs/dev-rewards/assets/42398278/a8e3599f-4475-4e8d-a568-4eb95517ca00)

**Comment by Bisstocuz** [comment]
I am using Microsoft Edge 122.0.2365.59

**Comment by akim-bow** [comment]
Try using different browser, e.g., Chrome. Also try cleaning all browser cache and local storage.
