### ISSUE TITLE
How to find the key pair that can claim your project token?

### ISSUE THREAD

**Issue by 106umao** [fluencelabs/dev-rewards#40]
Including virtual machines and remote servers, 7 of my computers are associated with my github account. Currently, the version of the ssh key that exists on my github account is not sure whether it contains a claimable key, so I now need to enumerate each computer. Each key to try to claim your token?

**Comment by 106umao** [comment]
What a fucking project hahaha

**Comment by 106umao** [comment]
Where can I find the key pair included in your snapshot version?
I hope you won’t waste too much of everyone’s time. It’s an honor for your project that developers are willing to claim your tokens. We can check the qualifications on the official website, but is it really appropriate for the application process to be so troublesome?

**Comment by 106umao** [comment]
It’s so funny, I briefly looked at the python code they wrote. It will download the file called metadata.json to the local, and then traverse and compare it with the entered key. . . . This is what they call a snapshot. . .

Does this mean that every developer with many key pairs needs to analyze your "Bad Smell Code" like me?

**Comment by 106umao** [comment]
The snapshot link is [](https://fluence-dao.s3.eu-west-1.amazonaws.com/metadata.json)
If you have the same situation, you don’t need to read "bad smell" anymore.

hhh

**Comment by akim-bow** [comment]
As you mentioned above, you can find eligible public keys for claiming in `metadata.json` file. Simple file search will do the trick. Closing as there is no particular issue now.
