### ISSUE TITLE
please create a manual way to claim the reward

### ISSUE THREAD

**Issue by christophsturm** [fluencelabs/dev-rewards#43]
I'm not going to let a script or docker container mess around with my private ssh key.

**Comment by christophsturm** [comment]
ok I found the manual instructions

**Comment by A7med3bdulBaset** [comment]
Can you give a link of it?

> ok I found the manual instructions

**Comment by christophsturm** [comment]
https://github.com/fluencelabs/dev-rewards/blob/main/MANUAL_INSTRUCTIONS.md
