### ISSUE TITLE
Username in github-accounts.{id}.txt but not in metadata.bin

### ISSUE THREAD

**Issue by KoryNunn** [fluencelabs/dev-rewards#44]
Is the list in https://claim.fluence.network/static/media/github-accounts.579a238639e5f9da5fd0.txt accurate?

**Comment by akim-bow** [comment]
Yes, the list should correspond the keys from metadata.bin file. Which usernames don't coincide?

**Comment by KoryNunn** [comment]
mine

**Comment by akim-bow** [comment]
Why? I've found your username both in metadata.bin and in the frontend file. Don't see an issue here.
<img width="1032" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/59872966/f19efc68-642a-4eee-8cbd-76da04b033c3">

**Comment by KoryNunn** [comment]
Ah, case sensitive, thankyou.
