### ISSUE TITLE
Generated proof have invalid format

### ISSUE THREAD

**Issue by Paraguanads** [fluencelabs/dev-rewards#46]
Hello! I generated the proof key following all the steps for claiming. Got the proof with the following message:

`Success! Copy the line below and paste it in the fluence airdrop website. THE_PROOF_STRING `

But when I'm trying to claim from the airdrop web UI it says that Proof have an invalid format. As long the proof is generated only with the correct keys as sine qua non condition, what can be the error I'm experiencing?

Thanks in advance! 🙋‍♂️

**Comment by Paraguanads** [comment]
Solved using Mozilla Firefox. Claim site seems to not be compatible with Brave browser.

**Comment by jc0803kevin** [comment]
是的，使用火狐浏览器可以正常领取
