### ISSUE TITLE
why don't support recently added ssh key?

### ISSUE THREAD

**Issue by nautaa** [fluencelabs/dev-rewards#47]
I got this tip.
> Your private key doesn't match your public key in GitHub. It could happen if you've changed local ssh key recently.

**Comment by akim-bow** [comment]
Keys, added after GitHub snapshot has been taken, not included and cannot be used for the claiming right now. Please follow the Fluence socials in case the situation will change later.
[Discord](https://fluence.chat/)
[Twitter](https://twitter.com/fluence_project)

**Comment by wufengtao1** [comment]
Because I replaced the key after the snapshot, I can't claim the airdrop anymore? Why is there such a stupid setup? Is there a problem with frequently changing keys for security? Who is your user growth director, and why such a foolish decision?
