### ISSUE TITLE
Generating proof fails if SSH directory contains some non-key files, like `.DS_Store`

### ISSUE THREAD

**Issue by mtrisic** [fluencelabs/dev-rewards#5]
# `dev-rewards` script will crash if target directory contains some non-key files, like `.DS_Store`

My `~/.ssh/` directory contained `.DS_Store` file, generated by macOS. 
Script crashed after entering username for checking for availability with an error:

```shell
docker run -it -v ~/.ssh:/root/.ssh dev-reward-script

.....  step2: 

Ethereum wallet address is necessary to generate a proof that you will send through our web page.
Important notice: you need to make a claim transaction from the entered address!

Enter the ethereum address to which you plan to receive the airdrop:
0x.......[REDACTED] 

Traceback (most recent call last):
  File "/claim/python/proof.py", line 157, in <module>
    main()
  File "/claim/python/proof.py", line 141, in main
    sshPubKey, sshKeyPath = choose_ssh_key()
  File "/claim/python/proof.py", line 61, in choose_ssh_key
    if not is_ssh_key(path):
  File "/claim/python/proof.py", line 96, in is_ssh_key
    key = file.read()
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 560: invalid start byte
``` 

Removing `.DS_Store` file fixes error.

**Comment by leo-web3** [comment]
def choose_ssh_key():
    files = []
    try:
        files = os.listdir(SSH_KEYS_DIR)
    except FileNotFoundError:
        pass

    sshKeys = []
    for f in files:
        if f == '.DS_Store':
            continue
        path = os.path.join(SSH_KEYS_DIR, f)
        if not is_ssh_key(path):
            continue
        sshKeys.append(path)

**Comment by snadorp** [comment]
Fixed here: https://github.com/fluencelabs/dev-rewards/pull/3
