### ISSUE TITLE
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

### ISSUE THREAD

**Issue by wufengtao1** [fluencelabs/dev-rewards#53]
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

WTF? Because I replaced the key after the snapshot, I can't claim the airdrop anymore? Why is there such a stupid setup? Is there a problem with frequently changing keys for security? Who is your user growth director, and why such a foolish decision?

**Comment by du5** [comment]
The newly added temporary key cannot be verified, non support for hardware keys This is a very bad decision

**Comment by phryneas** [comment]
Hi there :)

Is there a chance that the `metadata.bin` might get regenerated at some point with newly added keys? 
I am using a hardware token, and `age` cannot access that, so I had to add a new ssh-key in the hopes you'll pick that up after a while.

**Comment by L-Qun** [comment]
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

Is there any way to solve?

**Comment by wufengtao1** [comment]
This is truly the dumbest airdrop in history.

**Comment by akim-bow** [comment]
Dublicate of #63
