### ISSUE TITLE
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

### ISSUE THREAD

**Issue by L-Qun** [fluencelabs/dev-rewards#56]
Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

Is there any way to solve?

**Comment by L-Qun** [comment]
Is there any other way to verify

**Comment by L-Qun** [comment]
Is it possible to regenerate a new metadata.json file based on the updated ssh key

**Comment by L-Qun** [comment]
To be honest, this is my first airdrop

**Comment by folex** [comment]
Hello! Thanks for reaching out!

Please take a look at our Governance Forum. A lot of answers have been given and fired out there:

https://gov.fluence.network/t/developer-rewards-cannot-be-claimed-due-to-lost-ssh-keys/74

**Comment by L-Qun** [comment]
But I didn't find any solution on your Governance Forum.

**Comment by L-Qun** [comment]
> Hello! Thanks for reaching out!
> 
> Please take a look at our Governance Forum. A lot of answers have been given there:
> 
> https://gov.fluence.network/t/developer-rewards-cannot-be-claimed-due-to-lost-ssh-keys/74

Could you please provide another way to verify or update metadata.json file base on the new snapshot?

**Comment by L-Qun** [comment]
@folex
