### ISSUE TITLE
Proof is invalid format

### ISSUE THREAD

**Issue by niclash** [fluencelabs/dev-rewards#58]
I got the Success in proof.py,

```
Now the script needs your ssh key to generate proof. Please, enter path for github SSH key:
/root/.ssh/github_rsa

Success! Copy the line below and paste it in the fluence airdrop website.
34380,0xfddca5eb422748681028c4f7f3e140f2730753a9,0x9d2545bb2ef5de73fd4515ed2d3faf5f0597130e890515b2ca49cd71a31: 
<snip/>
: MmU0NWRhYTAwZGQwYjJiMyIsICIweGViNTZjNWI4YTcyMDgzZjA0ZDQxOGJhODAyMjYxODAxY2JmZmJlOGU2OTBhNWRjY2MyNjVmMzJhYzlkYjIyNDAiLCAiMHg5ZDdmZGY2N2ZiYWZhZTljYzVjMWY2MTVhYzFkNTQ4NGVhNDdkN2FmNzJiODEzNWNhOWQ2MmQ1OWYwZDgwNzZhIiwgIjB4MmNmYTA5ZWVlM2U4NjE1NDVjMzhiMjgxYWJhMmYxNTU0YWM3YzE3Y2Q2OWNjNWEwMWY4MzUxM2E5OGQ4Mjc0ZCIsICIweDgzMjI4NzU5MDhjYzRkMWFiODg5ODBhMjg5MzQ1ODJlNDBkYzAzNGQ1NjQ0MjAwZDdhZGJjODkwZDE5MzU3YzYiLCAiMHg0Y2NiMjFkMTkyOWU3ODg3M2MyYjM4YTFmYjQ4NDc0NjhmNGE1NGI2YmVhOTA3NTZmZTNkMDRmOTEyZTdlNmUyIl0=

But copying the line to the web form, gives the information in top right corner "Proof has invalid format"

The form says that a base64 should be copied, but the output is 4 comma-separated values, where the last is base64 json doc. Neither all nor just the base64 json works for me.

**Comment by puxiao** [comment]
https://github.com/fluencelabs/dev-rewards/issues/31#issuecomment-1979044929

You have to do it all over again.

1. Clear cache data
2. Revisit: https://claim.fluence.network/
3. Re-enter github name
   ....

That's what I just did, successful.

**Comment by boneyard93501** [comment]
https://github.com/fluencelabs/dev-rewards/issues/58

**Comment by jc0803kevin** [comment]
> [#31 (comment)](https://github.com/fluencelabs/dev-rewards/issues/31#issuecomment-1979044929)
> 
> You have to do it all over again.
> 
> 1. Clear cache data
> 2. Revisit: https://claim.fluence.network/
> 3. Re-enter github name
>    ....
> 
> That's what I just did, successful.

清除过浏览器的缓存，proof是通过docker build之后启动容器生成的，同样出现了这个问题

**Comment by puxiao** [comment]
> 清除过浏览器的缓存，proof是通过docker build之后启动容器生成的，同样出现了这个问题

只要 github 的私钥不变，每次生成的证书内容是完全相同的，不需要每次都执行生成一遍。

我这边之前也遇到这个情况，我只是刷新 https://claim.fluence.network/ 重头再来，就没一点问题了。
(谷歌浏览器)

不过我刚开始弄，我往我的 metamask 转了 ETH，可是 一直不到账，提取时说我没足够交易手续费，无法提取。

**Comment by niclash** [comment]
Yes, the recommended $35 in transaction fee is ridiculous. I offered $8, and transaction is not going through. ETH is getting more and more useless.

**Comment by sshine** [comment]
python 或 docker 方法都不起作用。

尝试了使用多个私钥。

幸运的是，这个 github issue 已经解决了，所以没有问题。
