### ISSUE TITLE
How to use this with Yubikey? 

### ISSUE THREAD

**Issue by lana-shanghai** [fluencelabs/dev-rewards#60]
Could you please kindly add a guide on how to decrypt whatever needs to be decrypted using Yubikey? Thanks!

**Comment by lana-shanghai** [comment]
OK, fantastic, you cannot decrypt files with Yubikey. Which genius came up with this proof generation process?.. Of course many people sign off commits with Yubikey.

**Comment by boneyard93501** [comment]
https://github.com/fluencelabs/dev-rewards/issues/48
