### ISSUE TITLE
Could you please provide another way to verify?

### ISSUE THREAD

**Issue by L-Qun** [fluencelabs/dev-rewards#63]
I love Fluence. However, many people have contributed to Web3, but due to SSH key issues, they are unable to receive rewards. I believe this was not your original intention. I hope there can be a new method to verify and authorize.

**Comment by bel0v** [comment]
My main issue here is that you have to give your private ssh keys. This is like basic stuff, you don't give your private keys to "prove" anything. You can sign stuff with private keys and 3rd party can verify it **without knowing your private keys**, just pls read how key encryption works guys.

**Comment by L-Qun** [comment]
![img_v3_028r_f5928b6b-78bd-4d6d-9a9b-ad6ad7537ahu](https://github.com/fluencelabs/dev-rewards/assets/68707557/b9655ceb-d58b-4349-b25c-cfa0fb249477)

**Comment by L-Qun** [comment]
@bel0v What I mean is that many people accidentally update id_rsa file or replace their computer after snapshot

**Comment by wufengtao1** [comment]
This is truly the dumbest airdrop in history.

**Comment by Bo0tstrap** [comment]
> This is truly the dumbest airdrop in history.

Yes

**Comment by AndreyGrin** [comment]
I have same issue, got new laptop and my key is not eligible anymore...

**Comment by ildarzf** [comment]
I also lost access to my old SSH keys. Please make a new Github verification method or allow new SSH keys for verification.

**Comment by fyzhu** [comment]
after 2623.9s downloading I failed

**Comment by fyzhu** [comment]
I got proof finally, but I failed
![image](https://github.com/fluencelabs/dev-rewards/assets/5175751/189bbbd2-3334-49d4-baac-d94c1c77dbc1)

**Comment by akim-bow** [comment]
Dublicate of #47
