### ISSUE TITLE
Invalid signature. Are you using the same wallet you specified in proof generation? 

### ISSUE THREAD

**Issue by shaflow01** [fluencelabs/dev-rewards#64]
When I use bash to create a proof, it is successful. However, when I submit it, I receive an "Invalid signature. Are you using the same wallet you specified in proof generation?". I then tried using Docker, but encountered a different error stating "Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation." Despite verifying that my RSA keys in the metadata.json file are the same.
In addition, is the content after the equal sign of the RSA public key in metadata.json the encoding of an email address? The RSA public key stored locally on my machine has an email address after it.

**Comment by shaflow01** [comment]
Version compatibility issue, I have used an updated version of the system

**Comment by zhongjiajie** [comment]
> Version compatibility issue, I have used an updated version of the system

@shaflow01  hi, may I ask which version you use? I missing the same issue during the proof process

**Comment by shaflow01** [comment]
Ubuntu22.04.3

**Comment by timfaner** [comment]
same issue. Don't know where goes wrong

**Comment by SCBuergel** [comment]
same here, I am using the bash script to generate the proof with an ed25519 key, the script does generate the proof but submitting it on the website gives the same error as OP. Interestingly before any metamask popup.

**Comment by jediadolf** [comment]
same issue. windows
