### ISSUE TITLE
Where is the source of metadata.bin?

### ISSUE THREAD

**Issue by Nexus2k** [fluencelabs/dev-rewards#65]
There's no chance I run some random binary on my machine for a token that's not even listed on coinmarketcap.com please provide the source of metadata.bin that the bash verification method is loading.

**Comment by aayusharyan** [comment]
Hahaha, you expect developers to do that for a token that isn't even listed, nice.

**Comment by boneyard93501** [comment]
https://github.com/fluencelabs/dev-rewards/blob/0cd41bcfb1ef07dce92390c88b0c160665ae10d3/MANUAL_INSTRUCTIONS.md?plain=1#L12
