### ISSUE TITLE
Claim fails with 'invalid hash argument="value"'

### ISSUE THREAD

**Issue by S0raWasTaken** [fluencelabs/dev-rewards#67]
Console output:
```invalid hash (argument="value", value="f903...", code=INVALID_ARGUMENT, version=providers/5.7.2)```

Using:
- Librewolf browser (Tried with Chromium)
- GateWeb3 Wallet
- Python proof (Didn't want to mess with the sha3sum binary)

**Comment by akim-bow** [comment]
Can you show the browser console logs? And remember to show any stacktraces if there are ones.

**Comment by xming521** [comment]
I also made a mistake in the last step. A Chromium browser 
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/c1fa6b8d-2785-415e-8267-40f4e0b6cf6c)
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/b708b92c-05b0-4289-9741-c27ae3e07bd1)


@akim-bow

**Comment by xming521** [comment]
I also made a mistake in the last step. a Chromium browser 
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/9cb019eb-b653-447d-a53d-77f95dd0c24e)
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/cb5e2dde-3318-4868-baa5-dd7baa674baa)

@akim-bow

**Comment by akim-bow** [comment]
@xming521 need to submit signature first. You've skipped that.

**Comment by akim-bow** [comment]
@S0raWasTaken can you also try MetaMask?

**Comment by xming521** [comment]
I 100% didn’t and used Binance’s web3 wallet

**Comment by xming521** [comment]
@akim-bow  I didn't skip at all. I used Binance's web3 wallet.

**Comment by xming521** [comment]
I clicked on claim several times, but the page didn't   @akim-bow 
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/f3bd56cf-f618-4699-bea0-527bd4311a10)
![image](https://github.com/fluencelabs/dev-rewards/assets/32786500/4b878c78-1bc4-4dd5-a489-1ea74c895113)
