### ISSUE TITLE
governance.js:24 Cannot confirm that tokens are not claimed yet.

### ISSUE THREAD

**Issue by xuing** [fluencelabs/dev-rewards#70]
The reason is that the /proof page does not check the wallet connection status.

**Comment by akim-bow** [comment]
Check other issues related to this, e.g., #38 and #31. If nothing will help, please open another issue with the detailed description what went wrong, console screen, etc... Otherwise it's not possible to reproduce.

**Comment by xuing** [comment]
Actually, I've submitted a pull request to address the issue, preventing it from occurring again.
https://github.com/fluencelabs/dao/pull/22

**Comment by xuing** [comment]
> Check other issues related to this, e.g., #38 and #31. If nothing will help, please open another issue with the detailed description what went wrong, console screen, etc... Otherwise it's not possible to reproduce.

Actually, I've submitted a pull request to address the issue, preventing it from occurring again.
https://github.com/fluencelabs/dao/pull/22
