### ISSUE TITLE
Provide alternative verification methods to address SSH key issues

### ISSUE THREAD

**Issue by Louis-XWB** [fluencelabs/dev-rewards#73]
I am a big fan of Fluence and have been actively contributing to Web3. However, I came across an issue where many contributors are unable to claim their rewards due to SSH key problems. I believe this was not the original intention of the project.

According to my research, there are currently around a large number of contributors who are unable to claim rewards due to SSH key issues. These contributors include developers, testers, community members, etc., who have made significant contributions to the development of Fluence.

I believe that providing alternative verification methods will help more contributors receive the rewards they deserve and further develop the Fluence community.

**Comment by akim-bow** [comment]
Dublicate of #63
