### ISSUE TITLE
This method of claiming is insecure

### ISSUE THREAD

**Issue by klntsky** [fluencelabs/dev-rewards#75]
People should not let you unlock the private keys, ever.

>         AGE_URL="https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-darwin-amd64.tar.gz"

Congrats to @FiloSottile who can steal everyone's private keys by uploading a new release under that tag

**Comment by akim-bow** [comment]
Check out the instruction in `README.md`. You can generate signature in docker without giving the access to the network.
