### ISSUE TITLE
Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.

### ISSUE THREAD

**Issue by buba-ru** [fluencelabs/dev-rewards#82]
I am eligible for rewards based on github login verification here: claim.fluence.network
But when generating the confirmation, I get a message: `Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys added before our Github snapshot are supported for proof generation.`

My current key is added on github Mar 3, 2024

**Comment by akim-bow** [comment]
It's too late, snapshot has been taken before that date.
You can only use the keys listed in `metadata` files.
