### ISSUE TITLE
Is it safe to share private id_rsa key ?

### ISSUE THREAD

**Issue by q2333gh** [fluencelabs/dev-rewards#84]
I am not quite sure yet.

**Comment by akim-bow** [comment]
Depends on your trust. You actually share your private key with `age` utility only which uses it for decryption. They seem like good guys.

**Comment by q2333gh** [comment]
This issue is close too fast. i dont even understand yet~.

If the using private-key process is completely offline. 
I guess it will be safe .

**Comment by akim-bow** [comment]
There is an instruction to do everything in docker without network connection.
