### ISSUE TITLE
OSError: b'age: error: no identity matched any of the recipients

### ISSUE THREAD

**Issue by jeffreys-cat** [fluencelabs/dev-rewards#85]
![image](https://github.com/fluencelabs/dev-rewards/assets/11832969/ac1a55e5-95c1-4d7b-9f3c-96c96dbb151d)

OSError: b'age: error: no identity matched any of the recipients\nage: report unexpected or unhelpful errors at 
https://filippo.io/age/report\n'

**Comment by akim-bow** [comment]
It looks like your private key doesn't match with the public one used for message enryption.
Verify that your public key matches the one listed in `metadata.json` file.

**Comment by jeffreys-cat** [comment]
> It looks like your private key doesn't match with the public one used for message encryption. Verify that your public key matches the one listed in `metadata.json` file.

Got it, Thanks!
