### ISSUE TITLE
Specific file does not exist

### ISSUE THREAD

**Issue by rejep10** [fluencelabs/dev-rewards#87]
hi i have issue with my public key
my ssk jey located at C:\Users\rejep\.ssh
i pasted this location but got  Specific file does not exist

what should i do?
![photo_2024-03-20_17-43-00](https://github.com/fluencelabs/dev-rewards/assets/113621262/b9dbc8d7-948b-423f-9547-bd7efddb1525)
![photo_2024-03-20_17-42-55](https://github.com/fluencelabs/dev-rewards/assets/113621262/9ad9a7f8-6c2d-42dc-b3f8-8534d10d0e0b)

**Comment by akim-bow** [comment]
Try use forward slashes or shield backward slashes, e.g., instead of `\` put `\\`.

**Comment by rejep10** [comment]
> Try using forward slashes or shield backward slashes, e.g., instead of `\` put `\\`.

Try both not helped
![image](https://github.com/fluencelabs/dev-rewards/assets/113621262/eba6b80b-5c3b-4b42-839e-e5120928c30a)
![image](https://github.com/fluencelabs/dev-rewards/assets/113621262/f86b31f3-f5f8-4405-b1bd-087ff6adce78)

**Comment by akim-bow** [comment]
C:/Users/rejep/.ssh/my_key.pub
or
C:\\Users\\rejep\\.ssh\\my_key.pub

**Comment by rejep10** [comment]
same problem(

**Comment by akim-bow** [comment]
If you mount your ssh key inside docker, then this path won't work. You need to type the path pointing to file inside docker, not in your local Windows system.
Check docker volume mounting [docs](https://docs.docker.com/storage/volumes/). 
Also refer here #12
