### ISSUE TITLE
Open up the ability to confirm github via the site or other means.

### ISSUE THREAD

**Issue by 88Mikhail88** [fluencelabs/dev-rewards#88]
**Open up the ability to confirm github via the site or other means.**

_Good day. My github profile is eligible to receive FLT tokens, but I can't pass the verification because I have never created SSH keys. I use Personal access tokens (classic) for work - and I always limit it to project deadlines._ 

**I would appreciate it if you could solve my problem.**

**Comment by akim-bow** [comment]
Dublicate of #63

**Comment by 88Mikhail88** [comment]
Can you please tell me what to do?
Is there a solution?
