### ISSUE TITLE
ssh Added on Jul 27, 2023, Specified SSH key is not eligible for claiming. Only RSA and Ed25519 keys are supported for proof generation.

### ISSUE THREAD

**Issue by leo-web3** [fluencelabs/dev-rewards#9]
<img width="188" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/73073736/455eb6da-c166-4137-87de-49573268d856">
<img width="220" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/73073736/7c19961b-f652-4926-80b8-1e4e5beb21d4">
<img width="670" alt="image" src="https://github.com/fluencelabs/dev-rewards/assets/73073736/a15b3758-34a8-498d-af12-d6f7cdce2d38">

**Comment by IsQiao** [comment]
same problem

**Comment by elshan-eth** [comment]
Please, find yourself in metadata.json and check that you are using the correct key
