### ISSUE TITLE
Learn how to run scripts on iOS devices.

### ISSUE THREAD

**Issue by Dilrong** [fluencelabs/dev-rewards#93]
I'm not using SSH keys on my PC, but on my iPhone and iPad devices, so here's how to check it on a mobile device.

- Install ish from the app store.
- Run ish.
- `apk add git python3 curl`
- `git clone https://github.com/fluencelabs/dev-rewards.git`
- `cd dev-rewards`
- `curl https://fluence-dao.s3.eu-west-1.amazonaws.com/metadata.json > metadata.json`
- `python3 -m venv claim-venv`
- `source claim-venv/bin/activate`
- `pip3 install -r python/requirements.txt`
- `python3 python/proof.py`
- input your github name (It should be case sensitive)
- input your key path

**Comment by Dilrong** [comment]
If anyone knows the SSH keypath for IOS, please let me know! I'm currently looking for it, but don't know where it is.

**Comment by Dilrong** [comment]
IOS is stored in the keychain so there is no separate file path.
I'm using an app called workingcopy and when I inquired, I was told to do export key from the app function.

**Comment by boneyard93501** [comment]
> If anyone knows the SSH keypath for IOS, please let me know! I'm currently looking for it, but don't know where it is.

if the dir exists, it should be in ~/.ssh. if you are looking for the dir, depending on the app you're using, you have got to make sure hidden dirs/files are shown.

you can export from the ios keychain, see https://support.apple.com/sr-rs/guide/keychain-access/kyca35961/mac . depending on what export options you have, you may need to convert the exported key from p.12 to ssh format. you can do that with openssl, see https://stackoverflow.com/questions/18230558/export-public-key-from-an-p12-file

**Comment by Dilrong** [comment]
> > If anyone knows the SSH keypath for IOS, please let me know! I'm currently looking for it, but don't know where it is.
> 
> if the dir exists, it should be in ~/.ssh. if you are looking for the dir, depending on the app you're using, you have got to make sure hidden dirs/files are shown.
> 
> you can export from the ios keychain, see https://support.apple.com/sr-rs/guide/keychain-access/kyca35961/mac . depending on what export options you have, you may need to convert the exported key from p.12 to ssh format. you can do that with openssl, see https://stackoverflow.com/questions/18230558/export-public-key-from-an-p12-file

Thanks for the feedback, I can do it on Mac, but it doesn't seem to work on my iPhone and iPad like it does on my Mac. I'm using an app called workingcopy, and it supports exporting, which solved the problem.
