### ISSUE TITLE
`metadata.bin` should be compressed.

### ISSUE THREAD

**Issue by xkszltl** [fluencelabs/dev-rewards#96]
Compression with `xz -kevT0 metadata.bin` shows a compression ratio of `~0.52`.
This is significant enough to reduce this 1GB file to 0.5GB, a massive save in egress cost and download time.

**Comment by xkszltl** [comment]
Also tried a few more options:
- `gzip -9kv metadata.bin`: ~0.56
- `zest --progress -19 -k -T0 metadata.bin`: ~0.5

**Comment by akim-bow** [comment]
I agree with your proposal, that definitely would be nice.
But keeping in mind that airdrop has started some time ago and many people did the claiming already, the efforts won't worth it. So now it is not planned, bugs and issues are priorities.
